namespace AICentralTests.TestHelpers;

public static class FakeStreamingResponseContent
{
    public static string Response = """
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"role":"assistant"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"There"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" once"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" was"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" a"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" man"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" with"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" a"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" plan"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"\n"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"To"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" write"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" a"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" test"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" for"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" Open"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"AI"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"'s"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" chat"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"bot"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" clan"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"\n"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"He"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" typed"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" and"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" he"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" typed"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":","}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" but"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" alas"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"\n"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"His"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" brain"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" was"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" scrambled"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" like"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" eggs"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" in"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" a"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" glass"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"\n\n"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"He"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" tried"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" to"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" ask"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" for"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" help"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" from"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" a"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" friend"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"\n"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"But"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" they"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" were"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" busy"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" with"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" a"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" task"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" that"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" never"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" ends"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"\n"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"So"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" he"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" sat"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" there"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" alone"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":","}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" in"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" despair"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"\n"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"Wonder"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"ing"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" if"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" his"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" chat"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"bot"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" test"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" would"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" ever"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" be"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":" fair"}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"."}}]}
                                    data: {"id":"chatcmpl-8V9BJfiDsC9QPMDdJrfN2GfrREYIX","object":"chat.completion.chunk","created":1702434153,"model":"gpt-35-turbo","choices":[{"finish_reason":"stop","index":0,"delta":{}}]}
                                    data: [DONE]
                                    """;
}